version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./my_marvin.yml:/usr/share/jenkins/ref/jenkins.yaml
      - ./job_dsl.groovy:/usr/local/job_dsl.groovy
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
